### ISSUE TITLE
Tuning etcd parameters

### ISSUE THREAD

**Issue by alemacci** [Vonng/pigsty#194]
According to https://etcd.io/docs/v3.4/tuning/

We can tune ETCD_ELECTION_TIMEOUT and ETCD_HEARTBEAT_INTERVAL (milliseconds).

Defaults are
```
ETCD_ELECTION_TIMEOUT="1000"
ETCD_HEARTBEAT_INTERVAL="100"
```

Which I think they are too low. Perhaps we can tune them to
```
ETCD_ELECTION_TIMEOUT="5000"
ETCD_HEARTBEAT_INTERVAL="1000"
```

And set into etcd/defaults/main.yml ?

Also, giving the possibility to the user to customize them (due to specific network/disks environment where latency may differ from optimal conditions) can be interesting.

**Comment by Vonng** [comment]
That's great.

We can introduce two new parameters:

`etcd_election_timeout`: 1000
`etcd_heartbeat_interval`: 1000

Since there's several constraints:

* etcd_heartbeat_interval ≈ max(member RTT) ≈ [0.5,1.5]xRTT
* etcd_heartbeat_interval <= 5s
* etcd_election_timeout >= 10 * etcd_heartbeat_interval
* etcd_election_timeout <= 50s

100ms interval looks reasonable in the same DC, maybe we can leave that intact, and use a 5s election timeout from the beginning?

**Comment by Vonng** [comment]
done by https://github.com/Vonng/pigsty/commit/56c631cf7ff806de87e34fb4c69d50e85b3784dd
