### ISSUE TITLE
pg_profile feature

### ISSUE THREAD

**Issue by alemacci** [Vonng/pigsty#217]
It would be useful to have a snapshot-based workload repository such as pg_profile.

It acts like Oracle Statspack / AWR, helping you find out resource-intensive activities.

https://github.com/zubkov-andrei/pg_profile

Report example: https://github.com/zubkov-andrei/pg_profile/blob/master/report_examples/pg15.html

**Comment by Vonng** [comment]
AWR-like reporting would be fascinating.  But if it requires an extra 3rd party kernel extension and is not maintained in the official pgdg repo, the cost may be higher than the benefit.

Since we already have all* the necessary monitoring data with even better granularity (hours to seconds) in a modern Prometheus & Grafana observability stack, I'd prefer to implement a better version with grafana dashboards.  And that would be the most fun part of this project.

I already have a set of hourly executed python/shell scripts to take snapshots from target Postgres instances and store them in the meta database hourly.  Yeah, that is the `meta` prepared for. One important thing it does is upsert SQL Query text from `pg_stat_statements` so you can view SQL content from dashboards. Which would be the only thing lack to achieve same or better reporting (which is work around by using PGCAT to access system catalog directly)

Maybe we instead have a scaffold for this routine patrol script to collect necessary data into `meta`.  And separated reporting with grafana dashboards.
