### ISSUE TITLE
User facing frontend

### ISSUE THREAD

**Issue by kubeworkz** [Vonng/pigsty#241]
Has anyone attempted a front-end for Pigsty? By front-end I mean a simple User login / Create a Project (DB) / Get a connection string. That's pretty much it front-end. Much like Supabase or Neondatabase front-ends. I'm looking to start this as a service.

btw: I just fired up a fresh Rocky8 at Hetzner and it seems to hang on the alert manager:
```
TASK [infra : wait for alertmanager service online] ****************************************************************************************************************************
fatal: [65.109.83.37]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 127.0.0.1:9093"}
```

**Comment by Vonng** [comment]
https://vonng.github.io/pigsty/#/FAQ

Ansible command timeout (Timeout waiting for xxx）

The default ssh timeout for ansible command is 10 seconds, some commands may take longer than that due to network latency or other reasons.

You can increase the timeout parameter in the ansible config file [ansible.cfg](https://github.com/Vonng/pigsty/blob/master/ansible.cfg):

[defaults]
timeout = 10 # change to 60,120 or more


As for CLI, for GUI, here's an issue: https://github.com/Vonng/pigsty/issues/41

and a legacy cli tools: https://github.com/Vonng/pigsty-cli

**Comment by kubeworkz** [comment]
Great, thanks for the info.

**Comment by Vonng** [comment]
alertmanger is not a critical service , maybe try skipping that with tags or comment related tasks

**Comment by kubeworkz** [comment]
Cool, so I've got this up: http://65.109.83.37/ Do I need to setup nginx to get the links working?

**Comment by kubeworkz** [comment]
Do they need to be pigsty domain or can they be anything?

**Comment by Vonng** [comment]
Then you will have to apply it by yourself or using tools such as let's encrypt. and replace nginx config with ssl certs issued by public CA
