### ISSUE TITLE
CentOS 7.9 64位 SCC版安装失败

### ISSUE THREAD

**Issue by NJCHello** [Vonng/pigsty#375]
TASK [pgsql : install postgres extensions] ************************************************************************************************************
failed: [172.28.172.197] (item=postgis34_${pg_version}* timescaledb-2-postgresql-${pg_version}* pgvector_${pg_version}* hydra_${pg_version}*) => {"ansible_loop_var": "item", "changed": false, "item": "postgis34_${pg_version}* timescaledb-2-postgresql-${pg_version}* pgvector_${pg_version}* hydra_${pg_version}*", "msg": "No package matching 'postgis34_15*' found available, installed or updated", "rc": 126, "results": ["No package matching 'postgis34_15*' found available, installed or updated"]}

PLAY RECAP ********************************************************************************************************************************************
172.28.172.197             : ok=215  changed=163  unreachable=0    failed=1    skipped=40   rescued=0    ignored=0   
localhost                  : ok=6    changed=3    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

**Comment by Vonng** [comment]
1. fixed in https://github.com/Vonng/pigsty/commit/372513e1105d616b00aaedff691b987c9705d21e

2. example build config for pg 12 : https://github.com/Vonng/pigsty/blob/v2.5.1/files/pigsty/build.yml

3. ./infra-rm.yml , ./pgsql-rm.yml As for other module, we don't offer uninstall script, but there are unsintall task in the playbooks, check the module docs for detail
