### ISSUE TITLE
Ubuntu 22.04 LTS Support

### ISSUE THREAD

**Issue by zyf2019** [Vonng/pigsty#53]

**Comment by Vonng** [comment]
As the document describes: It only support CentOS 7.x and equivalent OS.
Supporting other Linux distribution is not our highest priority for now.
To support ubuntu, One has to replace all rpm with deb and refactor ansible role `repo` and `node_pkgs`
contribution for this is always welcome~.

**Comment by zyf2019** [comment]
好，我能做些什么工作：1 所有 rpm 替换为 deb 应该是问题不大，需要您提供下 rpm列表。至于之后需要做什么，我可以边学习边做。

**Comment by inntran** [comment]
个人认为改发行版意义不大，甚至可以锁定发行版和版本。既然人工登陆修改配置是不推荐的，那什么发行版环境又有什么关系？

**Comment by kubeworkz** [comment]
Is Ubuntu supported yet? If not, I'd like to help. Cheers, Dave

**Comment by Vonng** [comment]
> Is Ubuntu supported yet? If not, I'd like to help. I'm looking to run Pigsty on Oracle Cloud Ampere Servers (arm64) They don't support CentOS. This is a great project. Cheers, Dave


Pigsty now does not support arm & Debian/ubuntu either. It now works on EL7,8,9 and its compatible release. 

Adding arm support to EL series cloud be easier since only repo & RPMs are involved. Debian/Ubuntu supported would be much more difficult since there's quite a huge difference between Debian & EL:

* Build deb repo, find mirrors, build missing deb
* Refactor node role to adjust Debian/Ubuntu node into the described status
* Make infra components grafana,prometheus,consul,etcd work on it.
* make pgsql,patroni,pgbouncer,haproxy,vip-manager work on debian/ubuntu.

Contributions are always welcome ~. Please let know if you are interested.

**Comment by kubeworkz** [comment]
Thanks for the reply. I was wondering if alien might help. It's a Ubuntu tool to convert .rpms to .deb format. Sure, it would be great to maybe try arm64 first.

**Comment by inntran** [comment]
Isn't Oracle Linux available on Oracle Cloud?

**Comment by kubeworkz** [comment]
I'll see if it's available on Ampere Servers.

**Comment by inntran** [comment]
Use Oracle Linux 8 should be fine. It's a rebuild from RHEL source.

**Comment by kubeworkz** [comment]
Ah, perfect. Thanks so much! I'll give it a try and let you know how it goes.

**Comment by kubeworkz** [comment]
So all we really need to is setup arm64 support. If you could let me know what needs to be changed I can do it if you like. Cheers, Dave

**Comment by Vonng** [comment]
> y instances setup at Oracle Cloud.

maybe arm version can be supported as simple as replacing all x86_64 to aarch64. but it require further testing.

SSL for postgres/pgbouncer/patroni/etcd/consul are added in v1.6.0 but not for nginx yet. Since you may have your own idea of applying & managing a real SSL certs rather than using a self-signed CA cert.

**Comment by kubeworkz** [comment]
Thanks

**Comment by Vonng** [comment]
TODO LIST

- [ ] install
  - [x] bootstrap
  - [x] configure
- [ ] API
  - repo_upstream
  - repo_packages
- [ ] node
  - [ ] node-id
  - [ ] tuned
  - [ ] chrony
  - [ ] dns
  - [ ] haproxy
  - [x] docker
  - [ ] etc...
- [ ] infra
  - [ ] local apt repo setup
  - [x] nginx
  - [x] dnsmasq
  - [x] grafana stack
  - [ ] prometheus stack: deb not found...
- [x] etcd 
- [ ] minio
- [ ] mongo
- [ ] redis
- [ ] pgsql
    - [x] pg16
    - [x] pg15
    - [x] pg misc: patroni, pgbouncer, pgbackrest, pgbadger, pg_exporter, vip-manager2
    - [ ] misc extensions

**Comment by Vonng** [comment]
Ubuntu 20.04 & 22.04 is supported, will be released in v2.5.0
