### ISSUE TITLE
How can I use it to monitor a new type of database？

### ISSUE THREAD

**Issue by mklzl** [Vonng/pigsty#79]
## such as mysql ， tidb and so on
    
    There should be a developer documentation to extend Pigsty

**Comment by mklzl** [comment]
@Vonng The label of issue should be provided for developer to choose .

**Comment by Vonng** [comment]
Well pigsty support PostgreSQL & Redis for now.
More databases will be added later (such as greenplum, citus, ck, mongo, maybe even mysql)

MySQL & TiDB support is not priority no.1 because:

1. I'm not a mysql & tidb expert
2. MySQL already have some popular monitoring tools such as pmm, so does tidb

It's quite straight forward to add support for MySQL since it's similar to PgSQL.
e.g deploy mysql exporters and replace dashboard metrics 

It's always welcome to contrib a MySQL integration 😊

**Comment by Vonng** [comment]
Pigsty now use catagorized modules: `INFRA`, `NODES`, `PGSQL`, `REDIS`.

Playbook, Config Vars, Grafana Dashboards,  Prometheus Targets.....

Just add new playbooks to deploy database & add monitoring targets to `/etc/prometheus/targets/<module>/*.yml` 

Detailed docs will be added later.
